const data = [
  {
    id: "1",
    name: "Jessica Jones",
    verified: true,
    prenium: false,
    physical_data: {
      age: "25",
      height: "5ft 10inches",
      weight: "84KG",
      bust_size: "small",
      skin_tone: "light skin",
      smoker: false,
      alcohol: true,
    },
    contact_data: {
      city: "Lekki",
      state: "lagos",
      country: "Nigeria",
      phone_number: "08171589973",
    },
    images: {},
    rates: {
      one_hour_rate: "15,000",
      two_hour_rate: "25,000",
      twentyfour_hour_rate: "50,000",
      weekend_rate: "100,000",
    },
    services: {
      OWO: true,
      OS: true,
      CIM: true,
      COF: false,
      COB: true,
      SC: true,
      DFK: false,
      AS: false,
      AR: false,
      SIXNINE: true,
      ST: false,
      EM: true,
      GS: false,
      Couples: true,
      GFE: true,
      Threesome: true,
      FF: false,
      ST: true,
      EB: false,
      Domination: true,
      LT: false,
    },
  },
  {
    id: "1",
    name: "amy whinehouse",
    verified: true,
    prenium: false,
    physical_data: {
      age: "25",
      height: "5ft 10inches",
      weight: "84KG",
      bust_size: "Medium(M)",
      skin_tone: "light skin",
      smoker: false,
      alcohol: true,
    },
    contact_data: {
      city: "Benin City",
      state: "edo",
      country: "Nigeria",
      phone_number: "08171589973",
    },
    images: {},
    rates: {
      one_hour_rate: "15,000",
      two_hour_rate: "25,000",
      twentyfour_hour_rate: "50,000",
      weekend_rate: "100,000",
    },
    services: {
      OWO: true,
      OS: true,
      CIM: true,
      COF: false,
      COB: true,
      SC: true,
      DFK: false,
      AS: false,
      AR: false,
      SIXNINE: true,
      ST: false,
      EM: true,
      GS: false,
      Couples: true,
      GFE: true,
      Threesome: true,
      FF: false,
      ST: true,
      EB: false,
      Domination: true,
      LT: false,
    },
  },
  {
    id: "1",
    name: "jess Jones",
    verified: true,
    prenium: false,
    physical_data: {
      age: "25",
      height: "5ft 10inches",
      weight: "84KG",
      bust_size: "large",
      skin_tone: "light skin",
      smoker: false,
      alcohol: true,
    },
    contact_data: {
      city: "Lekki",
      state: "Port Harcourt",
      country: "Nigeria",
      phone_number: "08171589973",
    },
    images: {},
    rates: {
      one_hour_rate: "15,000",
      two_hour_rate: "25,000",
      twentyfour_hour_rate: "50,000",
      weekend_rate: "100,000",
    },
    services: {
      OWO: true,
      OS: true,
      CIM: true,
      COF: false,
      COB: true,
      SC: true,
      DFK: false,
      AS: false,
      AR: false,
      SIXNINE: true,
      ST: false,
      EM: true,
      GS: false,
      Couples: true,
      GFE: true,
      Threesome: true,
      FF: false,
      ST: true,
      EB: false,
      Domination: true,
      LT: false,
    },
  },
  {
    id: "1",
    name: "Silva Jones",
    verified: true,
    prenium: false,
    physical_data: {
      age: "25",
      height: "5ft 10inches",
      weight: "84KG",
      bust_size: "medium",
      skin_tone: "light skin",
      smoker: false,
      alcohol: true,
    },
    contact_data: {
      city: "Lekki",
      state: "abuja",
      country: "Nigeria",
      phone_number: "08171589973",
    },
    images: {},
    rates: {
      one_hour_rate: "15,000",
      two_hour_rate: "25,000",
      twentyfour_hour_rate: "50,000",
      weekend_rate: "100,000",
    },
    services: {
      OWO: true,
      OS: true,
      CIM: true,
      COF: false,
      COB: true,
      SC: true,
      DFK: false,
      AS: false,
      AR: false,
      SIXNINE: true,
      ST: false,
      EM: true,
      GS: false,
      Couples: true,
      GFE: true,
      Threesome: true,
      FF: false,
      ST: true,
      EB: false,
      Domination: true,
      LT: false,
    },
  },
];

export default data;
